name: Greet New Issue

on:
  issues:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Add a comment to the new issue
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issueNumber = context.payload.issue.number;
          const commentBody = `
          👋 Hello @${context.payload.issue.user.login}! Thanks for opening this issue. We appreciate your contribution.
          
          Please provide as much detail as possible to help us resolve it quickly. If you have any screenshots or logs, feel free to add them here.
          
          Our team will review this issue and get back to you soon. In the meantime, check out our [documentation](link_to_documentation) for more information.
          
          Thanks again for your support!
          `;
          await github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            body: commentBody
          });
